SistemaWeb/Models/Categoria.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SistemaWeb.Models
{
    public class Categoria
    {
        public int Id { get; set; }

        public string Nome { get; set; }

        public string Descricao { get; set; }
    }
}

SistemaWeb/Models/Produtos.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SistemaWeb.Models
{
    public class Produtos
    {
        public int Id { get; set; }

        public string Nome { get; set; }

        public string Descricao { get; set; }

        public string Lote { get; set; }

        public Decimal Valor { get; set; }

        public string Fornecedor { get; set; }

        public int Quantidade { get; set; }

        public string Foto { get; set; }

        public DateTime DataCadastro { get; set; }
    }
}

SistemaWeb/Controllers/CategoriaController.cs
using SistemaWeb.Models;
using SistemaWeb.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SistemaWeb.Controllers
{
    public class CategoriaController : Controller
    {
        public ActionResult CadastrarCategoria(int? id)
        {
            Categoria categoria = new Categoria();
            if (id != 0 && id != null)
            {
                CategoriaDao cDao = new CategoriaDao();
                categoria = cDao.ListarCategoriaId(id);
            }
            ViewBag.Categoria = categoria;

            return View();
        }

        public ActionResult Cadastrar(Categoria categoria)
        {
            CategoriaDao cDao = new CategoriaDao();
            if (categoria.Id == 0)
            {
                cDao.Cadastrar(categoria);
                return RedirectToAction("CadastrarCategoria");
            }
            else
            {
                cDao.Edtar(categoria);
                return RedirectToAction("ListarCategoria");
            }
        }

        public ActionResult ListarCategoria()
        {
            CategoriaDao cDao = new CategoriaDao();
            ViewBag.Categoria = cDao.ListarCategoria();
            return View();
        }

        public ActionResult Deletar(int id)
        {
            CategoriaDao cDao = new CategoriaDao();
            cDao.Deletar(Convert.ToInt32(id));
            return Json(id);
        }
    }
}

SistemaWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SistemaWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

SistemaWeb/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SistemaWeb.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Login()
        {
            return View();
        }
    }
}

SistemaWeb/Controllers/ProdutosController.cs
using SistemaWeb.Models;
using SistemaWeb.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SistemaWeb.Controllers
{
    public class ProdutosController : Controller
    {
        public ActionResult CadastrarProdutos(int? id)
        {
            Produtos produtos = new Produtos();
            if (id != 0 && id != null)
            {
                ProdutosDao pDao = new ProdutosDao();
                produtos = pDao.ListarProdutosId(Convert.ToInt32(id));
            }

            ViewBag.Produtos = produtos;
            return View();
        }

        public ActionResult Cadastrar(Produtos produtos)
        {
            ProdutosDao pDao = new ProdutosDao();
            if (produtos.Id == 0)
            {
                produtos.DataCadastro = DateTime.Now;
                pDao.Cadastrar(produtos);
                return RedirectToAction("CadastrarProdutos");
            }
            else
            {
                pDao.Edtar(produtos);
                return RedirectToAction("ListarProdutos");
            }
        }

        public ActionResult ListarProdutos()
        {
            ProdutosDao pDao = new ProdutosDao();
            ViewBag.Produtos = pDao.ListarProdutos();
            return View();
        }

        public ActionResult Deletar(int id)
        {
            ProdutosDao pDao = new ProdutosDao();
            pDao.Deletar(Convert.ToInt32(id));
            return Json(id);
        }
    }
}

SistemaWeb/Views/Categoria/CadastrarCategoria.cshtml
@{
    ViewBag.Title = "Cadastrar Categoria";
}

<h2>Cadastrar Categoria</h2>

<br />

<div class="row">
    <div class="col-md-12">
        <form action="@Url.Action("Cadastrar","Categoria")">
            <input id="inputId" name="Id" value="@ViewBag.Categoria.Id" hidden />
            <div class="mb-3">
                <label for="inputNome" class="form-label">Nome</label>
                <input type="text" class="form-control" value="@ViewBag.Categoria.Nome" name="Nome" id="inputNome">
            </div>
            <div class="mb-3">
                <label for="inputDescricao" class="form-label">Descrição</label>
                <input type="text" class="form-control" value="@ViewBag.Categoria.Descricao" name="Descricao" id="inputDescricao">
            </div>
            <div class="mb-3 form-check">
                <br />
            </div>
            <button type="submit" class="btn btn-success">Salvar</button>
            <a type="button" href="@Url.Action("ListarCategoria","Categoria")" class="btn btn-danger">Cancelar</a>
        </form>
    </div>
</div>

SistemaWeb/Views/Categoria/ListarCategoria.cshtml
@{
    ViewBag.Title = "Listar Categoria";
}

<h2>Listar Categoria</h2>

<br />

<p>
    <a href="@Url.Action("CadastrarCategoria","Categoria")" class="btn btn-success">Cadastrar</a>
</p>
<body>
    <table class="table table-striped table-hover">
        <thead>
            <tr class="success">
                <th>Ações</th>
                <th>Nome</th>
                <th>Descricao</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in ViewBag.Categoria)
            {
                <tr>
                    <td>
                        <a href="@Url.Action("CadastrarCategoria","Categoria", new { id = item.Id})" style="margin-top: 20px;" class="btn btn-warning">Editar</a>
                        <a data-id="@item.Id" onclick="Apagar(this);" style="margin-top: 20px;" class="btn btn-danger">Apagar</a>
                    </td>
                    <td>
                        <p style="margin-top: 25px;">@item.Nome</p>
                    </td>
                    <td>
                        <p style="margin-top: 25px; "> @item.Descricao</p>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <!-- Modal -->
    <div class="modal fade" id="apagarModal" tabindex="-1" aria-labelledby="apagarModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Título do Modal</h4>
                </div>
                <div class="modal-body text-center">
                    <p>Deseja apagar esse produto??</p>
                </div>
                <div class="modal-footer">
                    <a class="btn btn-secondary" data-dismiss="modal">Fechar</a>
                    <a id="cadastrar" class="btn btn-primary">Save changes</a>
                </div>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
    <script src="~/Scripts/Customized/ListarProdutos.js"></script>
</body>

SistemaWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

SistemaWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SistemaWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

SistemaWeb/Views/Login/Login.cshtml
@{
    Layout = "~/Views/Shared/_Layout_Login.cshtml";
    ViewBag.Title = "Login";
}

<body class="text-center">
    <form class="form-signin">
        <img class="mb-4" src="../../assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
        <h1 class="h3 mb-3 font-weight-normal">Faça login</h1>
        <label for="inputEmail" class="sr-only">Endereço de email</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Seu email" required autofocus>
        <label for="inputPassword" class="sr-only">Senha</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Senha" required>
        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" value="remember-me"> Lembrar de mim
            </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
        <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>
    </form>
</body>

SistemaWeb/Views/Produtos/CadastrarProdutos.cshtml
@{
    ViewBag.Title = "Cadastrar Produtos";
}

<h2>Cadastrar Produtos</h2>

<br />

<div class="row">
    <div class="col-md-12">
        <form action="@Url.Action("Cadastrar","Produtos")">
            <input id="inputId" name="Id" value="@ViewBag.Produtos.Id" hidden />
            <div class="mb-3">
                <label for="inputNome" class="form-label">Nome</label>
                <input type="text" class="form-control" value="@ViewBag.Produtos.Nome" name="Nome" id="inputNome">
            </div>
            <div class="mb-3">
                <label for="inputDescricao" class="form-label">Descrição</label>
                <input type="text" class="form-control" value="@ViewBag.Produtos.Descricao" name="Descricao" id="inputDescricao">
            </div>
            <div class="mb-3">
                <label for="inputLote" class="form-label">Lote</label>
                <input type="text" class="form-control" value="@ViewBag.Produtos.Lote" name="Lote" id="inputLote">
            </div>
            <div class="mb-3">
                <label for="inputValor" class="form-label">Valor</label>
                <input type="number" class="form-control" value="@ViewBag.Produtos.Valor" name="Valor" id="inputValor">
            </div>
            <div class="mb-3">
                <label for="inputFornecedor" class="form-label">Fornecedor</label>
                <input type="text" class="form-control" value="@ViewBag.Produtos.Fornecedor" name="Fornecedor" id="inputFornecedor">
            </div>
            <div class="mb-3">
                <label for="inputQuantidade" class="form-label">Quantidade</label>
                <input type="number" class="form-control" value="@ViewBag.Produtos.Quantidade" name="Quantidade" id="inputQuantidade">
            </div>
            <div class="mb-3">
                <label for="inputFoto" class="form-label">Foto</label>
                <input type="text" class="form-control" value="@ViewBag.Produtos.Foto" name="Foto" id="inputFoto">
            </div>
            <div class="mb-3 form-check">
                <br />
            </div>
            <button type="submit" class="btn btn-success">Salvar</button>
            <a type="button" href="@Url.Action("ListarProdutos","Produtos")" class="btn btn-danger">Cancelar</a>
        </form>
    </div>
</div>

SistemaWeb/Views/Produtos/ListarProdutos.cshtml
@{
    ViewBag.Title = "Listar Produtos";
}

<h2>Listar Produtos</h2>

<br />

<p>
    <a href="@Url.Action("CadastrarProdutos","Produtos")" class="btn btn-success">Cadastrar</a>
</p>
<body>
    <table class="table table-striped table-hover">
        <thead>
            <tr class="success">
                <th>Ações</th>
                <th>Foto</th>
                <th>Nome</th>
                <th>Descricao</th>
                <th>Lote</th>
                <th>Valor</th>
                <th>Fornecedor</th>
                <th>Quantidade</th>
                <th>DataCadastro</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in ViewBag.Produtos)
            {
                <tr>
                    <td>
                        <a href="@Url.Action("CadastrarProdutos","Produtos", new { id = item.Id})" style="margin-top: 20px;" class="btn btn-warning">Editar</a>
                        <a data-id="@item.Id" onclick="Apagar(this);" style="margin-top: 20px;" class="btn btn-danger">Apagar</a>
                    </td>
                    <td>
                        <img src="@item.Foto" width="70" height="70">
                    </td>
                    <td>
                        <p style="margin-top: 25px;">@item.Nome</p>
                    </td>
                    <td>
                        <p style="margin-top: 25px; "> @item.Descricao</p>
                    </td>
                    <td>
                        <p style="margin-top: 25px; "> @item.Lote </p>
                    </td>
                    <td>
                        <p style="margin-top: 25px; "> @item.Valor </p>
                    </td>
                    <td>
                        <p style="margin-top: 25px; "> @item.Fornecedor </p>
                    </td>
                    <td>
                        <p style="margin-top: 25px;">  @item.Quantidade </p>
                    </td>
                    <td>
                        <p style="margin-top: 25px;">  @item.DataCadastro </p>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    ...
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>

    <script src="~/Scripts/Customized/ListarProdutos.js"></script>
</body>

SistemaWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="mais opções">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Nome do aplicativo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
                @Html.ActionLink("Produtos", "ListarProdutos", "Produtos", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Página Inicial", "Index", "Home")</li>
                        <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                        <li>@Html.ActionLink("Contato", "Contact", "Home")</li>*@
                    <li>@Html.ActionLink("Listar Produto", "ListarProdutos", "Produtos")</li>
                    <li>@Html.ActionLink("Listar Categoria", "ListarCategoria", "Categoria")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SistemaWeb/Views/Shared/_Layout_Login.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/LoginStyle.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="mais opções">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Nome do aplicativo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
                @Html.ActionLink("Produtos", "ListarProdutos", "Produtos", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Página Inicial", "Index", "Home")</li>
                        <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                        <li>@Html.ActionLink("Contato", "Contact", "Home")</li>*@
                    <li>@Html.ActionLink("Login", "Login", "Login")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>